CREATE TABLE IF NOT EXISTS OWNER (
  ID INT IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(255) NULL,
  PHONE VARCHAR(100) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
);

CREATE TABLE IF NOT EXISTS COMPANY (
  ID INT IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(100) NULL,
  PHONE VARCHAR(100) NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
);

CREATE TABLE IF NOT EXISTS OWNER_COMPANY (
  ID INT IDENTITY PRIMARY KEY,
  OWNER_ID INT NOT NULL,
  COMPANY_ID INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
);
